# Usando a imagem CentOS com suporte a systemd
FROM centos/systemd

# Informações do autor e da aplicação
LABEL author="Clebson Rosendo"
LABEL name="esus-app"
LABEL version="1.0"

# Ajustando repositórios do CentOS para usar o vault (arquivos antigos)
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum repolist enabled

# Instalando pacotes necessários e configurando o Java
RUN yum -y install file \
    && yum -y install wget \
    && yum clean all \
    && wget https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_linux-x64_bin.tar.gz \
    && mkdir /usr/lib/jvm/ \
    && tar zxvf openjdk-18.0.1.1_linux-x64_bin.tar.gz -C /usr/lib/jvm/ \
    && update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-18.0.1.1/bin/java 1065 \
    && rm openjdk-18.0.1.1_linux-x64_bin.tar.gz \
    && mkdir /home/downloads/

# Expondo portas usadas pela aplicação
EXPOSE 8080 80

# Criando um volume para armazenar dados da aplicação
VOLUME /opt/e-SUS/

# Configurando variáveis de ambiente para conexão com o banco de dados
# Note que o hostname do banco de dados deve ser ajustado para 'banco' devido à rede Docker
ENV APP_DB_URL=jdbc:postgresql://banco:5432/esus
ENV APP_DB_USER=postgres
ENV APP_DB_PASSWORD=esus

# Comando padrão de inicialização da imagem
CMD ["/usr/sbin/init"]
